# Generates a C++ translation unit embedding the game's default configuration files and
# its shipped levels.
#
# The game writes them into the user data folder the first time it cannot find a
# populated data folder, which is what lets it run without any system wide installation.
#
# Invoked from CMakeLists.txt as:
#   cmake -DOD_SOURCE_DIR=... -DOD_OUTPUT=... -P cmake/GenerateBuiltinData.cmake

if(NOT DEFINED OD_SOURCE_DIR OR NOT DEFINED OD_OUTPUT)
    message(FATAL_ERROR "GenerateBuiltinData.cmake requires OD_SOURCE_DIR and OD_OUTPUT")
endif()

# Only the files the game actually reads: the source tree also holds editor backups and
# other leftovers next to them, which have no business inside the executable.
file(GLOB_RECURSE OD_BUILTIN_FILES
     RELATIVE "${OD_SOURCE_DIR}"
     "${OD_SOURCE_DIR}/config/*.cfg"
     "${OD_SOURCE_DIR}/levels/*.level")
list(SORT OD_BUILTIN_FILES)

set(OD_ARRAYS "")
set(OD_ENTRIES "")
set(OD_INDEX 0)
set(OD_DIGEST_INPUT "")

foreach(OD_REL_PATH IN LISTS OD_BUILTIN_FILES)
    set(OD_ABS_PATH "${OD_SOURCE_DIR}/${OD_REL_PATH}")
    if(IS_DIRECTORY "${OD_ABS_PATH}")
        continue()
    endif()

    file(READ "${OD_ABS_PATH}" OD_HEX HEX)
    string(LENGTH "${OD_HEX}" OD_HEX_LENGTH)
    math(EXPR OD_SIZE "${OD_HEX_LENGTH} / 2")

    if(OD_SIZE EQUAL 0)
        # A zero sized array is not valid C++, so emit one padding byte and let the
        # recorded size stay at zero.
        set(OD_BYTES "0x00,")
    else()
        string(REGEX REPLACE "(..)" "0x\\1," OD_BYTES "${OD_HEX}")
        # Break the initialiser into short lines; a single multi-megabyte line makes some
        # compilers very unhappy.
        string(REGEX REPLACE "((0x..,){16})" "\\1\n" OD_BYTES "${OD_BYTES}")
    endif()

    string(APPEND OD_ARRAYS "const unsigned char file${OD_INDEX}[] = {\n${OD_BYTES}\n};\n\n")
    string(APPEND OD_ENTRIES "    { \"${OD_REL_PATH}\", file${OD_INDEX}, ${OD_SIZE} },\n")

    # Digest over names and contents, so that any edit to config/ or levels/ can be told
    # apart from the copy already extracted in the user folder.
    file(MD5 "${OD_ABS_PATH}" OD_FILE_MD5)
    string(APPEND OD_DIGEST_INPUT "${OD_REL_PATH}:${OD_FILE_MD5}\n")

    math(EXPR OD_INDEX "${OD_INDEX} + 1")
endforeach()

string(MD5 OD_DIGEST "${OD_DIGEST_INPUT}")

file(WRITE "${OD_OUTPUT}"
"// Generated by cmake/GenerateBuiltinData.cmake -- do not edit, do not commit.
#include \"utils/BuiltinData.h\"

namespace
{
${OD_ARRAYS}}

namespace BuiltinData
{
const File FILES[] = {
${OD_ENTRIES}};

const std::size_t FILE_COUNT = ${OD_INDEX};

const char* const CONTENT_DIGEST = \"${OD_DIGEST}\";
}
")

message(STATUS "Embedded ${OD_INDEX} default data files into ${OD_OUTPUT}")
